### PR TITLE
update recipe for v0.12.0

### PR DESCRIPTION
**Pull request by cokelaer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by cokelaer** [comment]
@mariusvniekerk @beckermr I have updated this recipe for version 0.12.0
There are 2 issues here with the feedstock complainging about ubuntu 16.04 not being available. 
Can you help me on this issue ? thanks

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by cokelaer** [comment]
@mariusvniekerk  thanks for the 'rerender'. I have now fixed the recipe and all checks have passed. I believe that someone on conda-forge should do the merge (not me) ? thanks

**Comment by mariusvniekerk** [comment]
If you're the feedstock maintainer feel free to merge it yourself

**Pull request merged**
