### PR TITLE
update version to 0.9.35

### PR DESCRIPTION
**Pull request by cokelaer**

### CODE REVIEW

**Comment by cokelaer** [comment]
@conda-forge-admin everything seems fine. how to merge the pull request so that the new version appears on conda-forge ? thanks

**Comment by ocefpaf** [comment]
I see that you are a maintainer on this feedstock, so you should have merge rights. Please let me know if that is not the case so we can fix r.

Note that self merges, particularly for version bumps, are OK in conda-forge.

**Comment by cokelaer** [comment]
@ocefpaf hum it looks like this is not the case or maybe I don't see the link. Here above in the "This branch has no conflicts with the base branch" it is written " Only those with write access to this repository can merge pull requests. " I do not see the  "merge" button.

**Comment by ocefpaf** [comment]
OK. I'll check what is going as soon as possible to give you the proper rights to this feedstock.

**Pull request merged**
