### PR TITLE
update easydev to 0.9.34 release

### PR DESCRIPTION
**Pull request by cokelaer**

### CODE REVIEW

**Comment by cokelaer** [comment]
@conda-forge-linter the CI (especially for osx) does not start. I was wondering whether I should be patient or if there is something to do to trigger the build. Thanks

**Review by ocefpaf — COMMENTED** [review]
Travis-CI is quite flaky lately. Since this is a simple update it is ok to merge without it but I recommend you to keep an eye on the master build later.

**Comment by cokelaer** [comment]
@ocefpaf since I do not have the admin write access (I guess), can someone do the merge ? Indeed, I cannot see any merge button on my interface. thanks

**Comment by ocefpaf** [comment]
You should get access b/c you are listed as a maintainer. But that can take some time to happen.

**Pull request merged**
